---
- hosts: all
  roles:
  #    - {role: git, tags: ['default']}
  #    - {role: ctags, tags: ['default']}
  #    - {role: silversearcher, tags: ['default']}
  #    - {role: console_theme, tags: ['default']}
  #    - {role: fonts, tags: ['default']}
  #    - {role: zsh, tags: ['default']}
  #    - {role: fzf, tags: ['default']}
  #    - {role: python, tags: ['python']}
  #    - {role: node, tags: ['nodejs']}
    - {role: haskell, tags: ['haskell']}
    - {role: neovim, tags: ['default']}
    - {role: tmux, tags: ['default']}
