sudo apt-get install git
sudo apt-get install tmux
cd /tmp
git clone https://github.com/Grin941/dotfiles.git
mv /tmp/dotfiles/tmux/.tmux* ~/

# Install powerline fonts
git clone https://github.com/ryanoasis/nerd-fonts.git --depth=1
cd nerd-fonts
./install.sh Hack
cd ../
rm -rf nerd-fonts/

# Set font
Open Terminal -> Right Click -> Profiles -> Profile Preferences -> General
Select Custom font -> Hack Regular
