sudo apt-get install git
sudo apt-get install vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
git clone https://github.com/Grin941/dotfiles.git
mv dotfiles/vim/.vim* ~/
cd ../
rm -rf dotfiles/
vim -> :PlugInstall

# Compile ycm
sudo apt-get install build-essential cmake python-dev
cd ~/.vim/plugged/youcompleteme
./install.py
