---
 - name: Install pyenv dependencies
   become: true
   apt:
     pkg: ["make", "build-essential", "libssl-dev", "zlib1g-dev", "libbz2-dev",
           "libreadline-dev", "libsqlite3-dev", "wget", "curl",
           "llvm", "libncurses5-dev", "libffi-dev", "liblzma-dev",
           "libncursesw5-dev", "xz-utils", "tk-dev"]
     state: latest
     update_cache: true
   tags: [default,python]
 
 - name: Install pyenv
   shell: |
     cd "{{ ansible_user_registered.home }}"
     curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
     /usr/bin/zsh -c "source {{ ansible_user_registered.home }}/.zshrc"
     /usr/bin/zsh -c "source {{ ansible_user_registered.home }}/.zshenv"
   tags: [default,python]
 
 - name: Update pyenv
   shell: "{{ ansible_user_registered.home }}/.pyenv/bin/pyenv update"
   tags: [default,python]

 - name: Install flake8
   become: true
   apt:
     pkg: ["flake8"]
     state: latest
     update_cache: true
   tags: [python]

 - name: Create flake8 folder
   file:
     path: "{{ ansible_user_registered.home }}/.config"
     state: directory

 - name: Configure flake8
   copy:
     src: flake8 
     dest: "{{ ansible_user_registered.home }}/.config/flake8"
     mode: 0664
   tags: [python]
