---
- name: Install ctags
  become: true
  apt:
    pkg: ["exuberant-ctags"]
    state: latest
    update_cache: true
    force_apt_get: yes

- name: Push ctags config
  copy:
    src: ctags
    dest: "{{ ansible_user_registered.home }}/.ctags"
    mode: 0664
