---
- name: Install zsh
  become: true
  apt:
    pkg: ["zsh"]
    state: latest
    update_cache: true

- name: Delete oh-my-zsh if exists
  become: true
  file:
    state: absent
    path: "{{ ansible_user_registered.home }}/.oh-my-zsh/"

- name: Delete .zshrc if exists
  become: true
  file:
    state: absent
    path: "{{ ansible_user_registered.home }}/.zshrc"

- name: Install oh-my-zsh
  shell: |
    cd "{{ ansible_user_registered.home }}"
    curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash

- name: Activate zsh
  become: true
  shell: chsh -s $(which zsh)

- name: Copy zshenv config files
  copy:
    src: zshenv 
    dest: "{{ ansible_user_registered.home }}/.zshenv"
    mode: 0664

- name: Copy zshrc config files
  copy:
    src: zshrc
    dest: "{{ ansible_user_registered.home }}/.zshrc"
    mode: 0664

- name: Install zsh-syntax-highlighting plugin
  git:
    repo: git://github.com/zsh-users/zsh-syntax-highlighting
    dest: "{{ ansible_user_registered.home }}/.oh-my-zsh/zsh-syntax-highlighting"

- name: Install zsh-autosuggestions plugin
  git:
    repo: git://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_user_registered.home }}/.oh-my-zsh/zsh-autosuggestions"

- name: Configure zsh plugins
  shell: /usr/bin/zsh -c "source {{ ansible_user_registered.home }}/.zshrc"
