---
- name: Install zsh
  apt:
    pkg: ["zsh"]
    state: latest
    update_cache: true

- name: Install oh-my-zsh
  shell: |
    curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    chsh -s $(which zsh)

- name: Copy zshenv config files
  copy:
    src: zshenv 
    dest: ~/.zshenv
    mode: 0664

- name: Copy zshrc config files
  copy:
    src: zshrc
    dest: ~/.zshrc
    mode: 0664

- name: Install zsh-syntax-highlighting plugin
  git:
    repo: git://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.oh-my-zsh/zsh-syntax-highlighting

- name: Install zsh-autosuggestions plugin
  git:
    repo: git://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/zsh-autosuggestions

- name: Configure zsh plugins
  shell: /usr/bin/zsh -c "source ~/.zshrc"
