---
- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_user_registered.home }}/.fzf"
    depth: 1

- name: Install fzf
  shell: |
    yes | "{{ ansible_user_registered.home }}/.fzf/install"
  
- name: Configure fzf
  shell: export FZF_DEFAULT_OPTS="--reverse --height=40%"
