---
- name: Install git
  apt:
    pkg: ["git"]
    state: latest
    update_cache: true

- name: Copy git configs
  copy:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    mode: 0664
  with_items:
    - { src: '../files/gitconfig', dest: '~/.gitconfig' }
    - { src: '../files/gitignore_global', dest: '~/.gitignore_global' }
