---
- name: Install git
  become: true
  apt:
    pkg: ["git"]
    state: latest
    update_cache: true

- name: Copy git configs
  copy:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    mode: 0664
  with_items:
    - { src: '../files/gitconfig', dest: '{{ ansible_user_registered.home }}/.gitconfig' }
    - { src: '../files/gitignore_global', dest: '{{ ansible_user_registered.home }}/.gitignore_global' }

- name: Apply gitignore_global
  git_config:
    name: core.excludesfile
    scope: global
    value: '{{ ansible_user_registered.home }}/.gitignore_global'

- name: Apply mergetool_cmd
  git_config:
    name: mergetool.fugitive.cmd
    scope: global
    value: 'vim -f -c "Gvdiff" "$MERGED"'

- name: Apply mergetool
  git_config:
    name: merge.tool
    scope: global
    value: 'fugitive'
