---
- name: Install tmux
  apt:
    pkg: ["tmux"]
    state: latest
    update_cache: true

- name: Install tmux plugins
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Copy tmux config
  copy:
    src: tmux.conf 
    dest: ~/.tmux.conf
    mode: 0664

- name: Activate tmux config
  shell: /usr/bin/zsh -c "source ~/.tmux.conf || true"
