---
- name: Install tmux
  become: true
  apt:
    pkg: ["tmux"]
    state: latest
    update_cache: true

- name: Install tmux plugins
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_user_registered.home }}/.tmux/plugins/tpm"

- name: Copy tmux config
  copy:
    src: tmux.conf 
    dest: "{{ ansible_user_registered.home }}/.tmux.conf"
    mode: 0664

- name: Activate tmux config
  shell: /usr/bin/zsh -c "source {{ ansible_user_registered.home }}/.tmux.conf || true"
