---
- name: Install tmux
  apt:
    pkg: ["tmux"]
    state: latest
    update_cache: true

- name: Install tmux plugins
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Configure tmux
  copy:
    src: tmux 
    dest: ~/
    mode: 664
  shell: source ~/.tmux.conf
