---
- name: Install nodejs
  become: true
  apt:
    pkg: ["nodejs", "npm"]
    state: latest
    update_cache: true
  tags: [default,nodejs]

- name: Add Yarn apt key
  become: true
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  become: true
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn

- name: Install Yarn
  become: true
  apt:
    name: yarn

- name: Install typescript
  become: true
  npm:
    name: typescript
    global: yes
  tags: [nodejs]

- name: Install prettier
  become: true
  npm:
    name: prettier
    global: yes
  tags: [nodejs]
