---
- name: Install neovim
  become: true
  apt:
    pkg: ["software-properties-common", "python3-dev", "python3-pip", "neovim"]
    state: latest
    update_cache: true
    force_apt_get: yes

- name: Install python neovim3
  shell: |
    "{{ ansible_user_registered.home }}"/.pyenv/bin/pyenv install 3.8.5
    "{{ ansible_user_registered.home }}"/.pyenv/bin/pyenv virtualenv 3.8.5 neovim3
    "{{ ansible_user_registered.home }}"/.pyenv/versions/neovim3/bin/pip install neovim

- name: Install nodejs neovim
  become: true
  npm:
    name: neovim
    global: yes

- name: Config nvim as vi alternative
  become: true
  alternatives:
    name: vi
    path: /usr/bin/nvim

- name: Config nvim as vim alternative
  become: true
  alternatives:
    name: vim
    path: /usr/bin/nvim

- name: Config nvim as editor alternative
  become: true
  alternatives:
    name: editor
    path: /usr/bin/nvim

- name: Install nvim plugins
  shell: |
    cd "{{ ansible_user_registered.home }}"
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Create nvim config folder
  file:
    path: "{{ ansible_user_registered.home }}/.config/nvim"
    state: directory
    recurse: yes

- name: Copy nvim config
  copy:
    src: init.vim 
    dest: "{{ ansible_user_registered.home }}/.config/nvim/init.vim"
    mode: 0664

- name: Activate nvim config
  shell: /usr/bin/zsh -c "source {{ ansible_user_registered.home }}/.config/nvim/init.vim || true"
