---
- name: Install python neovim2
  shell: pyenv install 2.7.15 && \
         pyenv virtualenv 2.7.15 neovim2 && \
         pyenv activate neovim2 && \
         pip install neovim && \
         pyenv deactivate

- name: Install python neovim3
  shell: pyenv install 3.7.1 && \
         pyenv virtualenv 3.7.1 neovim3 && \
         pyenv activate neovim3 && \
         pip install neovim && \
         pyenv deactivate

- name: Install nodejs neovim
  npm:
    name: neovim
    global: yes

- name: Install neovim requirement packages
  apt:
    pkg: ["software-properties-common", "python-dev", "python-pip", "python3-dev", "python3-pip"]
    state: latest
    update_cache: true

- name: Add neovim repository to apt
  apt_repository: add-apt-repository ppa:neovim-ppa/stable

- name: Install neovim
  apt:
    update_cache: yes
    pkg: ["neovim"]
    state: latest
    update_cache: true

- name: Configure vim alternatives
  shell: update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60 && \
         update-alternatives --config vi && \
         update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60 && \
         update-alternatives --config vim && \
         update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60 && \
         update-alternatives --config editor

- name: Install nvim plugins
  shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Copy & activate nvim config
  shell: mkdir ~/.config/nvim
  copy:
    src: neovim 
    dest: ~/.config/nvim
    mode: 664
  shell: source ~/.config/nvim/init.vim
