---
- name: Install neovim requirement packages
  become: true
  apt:
    pkg: ["software-properties-common", "python-dev", 
          "python-pip", "python3-dev", "python3-pip"]
    state: latest
    update_cache: true

- name: Install python neovim2
  shell: |
    "{{ ansible_user_registered.home }}"/.pyenv/bin/pyenv install 2.7.15
    "{{ ansible_user_registered.home }}"/.pyenv/bin/pyenv virtualenv 2.7.15 neovim2
    "{{ ansible_user_registered.home }}"/.pyenv/versions/neovim2/bin/pip install neovim

- name: Install python neovim3
  shell: |
    "{{ ansible_user_registered.home }}"/.pyenv/bin/pyenv install 3.7.1
    "{{ ansible_user_registered.home }}"/.pyenv/bin/pyenv virtualenv 3.7.1 neovim3
    "{{ ansible_user_registered.home }}"/.pyenv/versions/neovim3/bin/pip install neovim

- name: Install nodejs neovim
  npm:
    name: neovim
    global: yes

- name: Install neovim
  become: true
  apt:
    pkg: ["neovim"]
    state: latest
    update_cache: true

- name: Configure vim alternatives
  shell: |
    update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
    update-alternatives --config vi
    update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
    update-alternatives --config vim
    update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
    update-alternatives --config editor

- name: Install nvim plugins
  shell: |
    cd "{{ ansible_user_registered.home }}"
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Create nvim config folder
  file:
    path: "{{ ansible_user_registered.home }}/.config/nvim"
    state: directory
    recurse: yes

- name: Copy nvim config
  copy:
    src: init.vim 
    dest: "{{ ansible_user_registered.home }}/.config/nvim/init.vim"
    mode: 0664

- name: Activate nvim config
  shell: /usr/bin/zsh -c "source {{ ansible_user_registered.home }}/.config/nvim/init.vim || true"
