---
- name: Create local fonts folder
  file:
    path: ~/.local/share/fonts
    state: directory

- name: Copy Hack fonts
  copy:
    src: "{{ item.src }}" 
    dest: ~/.local/share/fonts
    mode: 0664
  with_items:
    - { src: '../files/Hack-Bold.ttf' }
    - { src: '../files/Hack-BoldItalic.ttf' }
    - { src: '../files/Hack-Italic.ttf' }
    - { src: '../files/Hack-Regular.ttf' }

- name: Apply system fonts
  shell: gconftool-2 --set /apps/gnome-terminal/profiles/Default/font --type string "Hack-Regular 12"

- name: Install powerline fonts
  apt:
    pkg: ["fonts-powerline"]
    state: latest
    update_cache: true
